version: '3'
services:
  jupyter-tutorial:
    build: .
    container_name: jupyter.local
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./work:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''
  mysql:
    image: mysql:5.7
    container_name: mysql.lab
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/data/db/
    environment:
      - MYSQL_ROOT_PASSWORD=iii
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb.lab
    ports:
      - "8000:8000"
    domainname: "cc104.dynamodb.local"
